// examples/example-vue/src/pages/adaptive-width.vue
<template>
  <Block title="Adaptive width using CSS" content-class="h-[300px] p-4" data-testid="block-adaptive-width-css">
    <Listbox v-model="selected">
      <Float
        as="div"
        class="relative"
        placement="bottom"
        :offset="4"
        floating-as="template"
      >
        <ListboxButton class="relative w-full bg-white pl-3.5 pr-10 py-2 text-left text-amber-500 text-sm leading-5 border border-gray-200 rounded-lg shadow-md">
          {{ selected.name }}
          <span class="absolute inset-y-0 right-0 flex items-center pr-2 pointer-events-none">
            <HeroiconsChevronUpDown20Solid class="w-5 h-5 text-gray-400" aria-hidden="true" />
          </span>
        </ListboxButton>

        <ListboxOptions class="w-full bg-white border border-gray-200 rounded-md shadow-lg overflow-hidden focus:outline-none">
          <ListboxOption
            v-for="person in people"
            v-slot="{ active, selected }"
            :key="person.name"
            :value="person"
            :disabled="person.unavailable"
            as="template"
          >
            <li
              class="relative block w-full pl-10 pr-3 py-2 text-left text-gray-600 text-sm cursor-default"
              :class="{
                'bg-amber-100 text-amber-700': active,
                'text-gray-300': person.unavailable,
              }"
            >
              <span class="block truncate" :class="selected ? 'font-medium' : 'font-normal'">
                {{ person.name }}
              </span>
              <span
                v-if="selected"
                class="absolute inset-y-0 left-0 flex items-center pl-3 text-amber-600"
              >
                <HeroiconsCheck20Solid class="w-5 h-5" aria-hidden="true" />
              </span>
            </li>
          </ListboxOption>
        </ListboxOptions>
      </Float>
    </Listbox>
  </Block>

  <Block title="Adaptive width using JS" content-class="h-[300px] p-4" data-testid="block-adaptive-width-js">
    <Listbox v-model="selected">
      <Float
        as="div"
        placement="bottom"
        :offset="4"
        floating-as="template"
        adaptive-width
        portal
      >
        <ListboxButton class="relative w-full bg-white pl-3.5 pr-10 py-2 text-left text-amber-500 text-sm leading-5 border border-gray-200 rounded-lg shadow-md">
          {{ selected.name }}
          <span class="absolute inset-y-0 right-0 flex items-center pr-2 pointer-events-none">
            <HeroiconsChevronUpDown20Solid class="w-5 h-5 text-gray-400" aria-hidden="true" />
          </span>
        </ListboxButton>

        <ListboxOptions class="bg-white border border-gray-200 rounded-md shadow-lg overflow-hidden focus:outline-none">
          <ListboxOption
            v-for="person in people"
            v-slot="{ active, selected }"
            :key="person.name"
            :value="person"
            :disabled="person.unavailable"
            as="template"
          >
            <li
              class="relative block w-full pl-10 pr-3 py-2 text-left text-gray-600 text-sm cursor-default"
              :class="{
                'bg-amber-100 text-amber-700': active,
                'text-gray-300': person.unavailable,
              }"
            >
              <span class="block truncate" :class="selected ? 'font-medium' : 'font-normal'">
                {{ person.name }}
              </span>
              <span
                v-if="selected"
                class="absolute inset-y-0 left-0 flex items-center pl-3 text-amber-600"
              >
                <HeroiconsCheck20Solid class="w-5 h-5" aria-hidden="true" />
              </span>
            </li>
          </ListboxOption>
        </ListboxOptions>
      </Float>
    </Listbox>
  </Block>
</template>

<script setup>
import { ref } from 'vue'
import { Listbox, ListboxButton, ListboxOption, ListboxOptions } from '@headlessui/vue'
import { Float } from '@headlessui-float/vue'
import Block from '@/components/Block.vue'
import HeroiconsCheck20Solid from '~icons/heroicons/check-20-solid'
import HeroiconsChevronUpDown20Solid from '~icons/heroicons/chevron-up-down-20-solid'

const people = [
  { id: 1, name: 'Durward Reynolds', unavailable: false },
  { id: 2, name: 'Kenton Towne', unavailable: false },
  { id: 3, name: 'Therese Wunsch', unavailable: false },
  { id: 4, name: 'Benedict Kessler', unavailable: true },
  { id: 5, name: 'Katelyn Rohan', unavailable: false },
]
const selected = ref(people[0])
</script>

// examples/example-react/src/pages/adaptive-width.jsx
import { Fragment, useState } from 'react'
import { Listbox } from '@headlessui/react'
import { Float } from '@headlessui-float/react'
import Block from '@/components/Block'
import HeroiconsCheck20Solid from '~icons/heroicons/check-20-solid'
import HeroiconsChevronUpDown20Solid from '~icons/heroicons/chevron-up-down-20-solid'

const people = [
  { id: 1, name: 'Durward Reynolds', unavailable: false },
  { id: 2, name: 'Kenton Towne', unavailable: false },
  { id: 3, name: 'Therese Wunsch', unavailable: false },
  { id: 4, name: 'Benedict Kessler', unavailable: true },
  { id: 5, name: 'Katelyn Rohan', unavailable: false },
]

export default function ExampleAdaptiveWidth() {
  const [selected, setSelected] = useState(people[0])

  return (
    <>
      <Block title="Adaptive width using CSS" contentClass="h-[300px] p-4" data-testid="block-adaptive-width-css">
        <Listbox value={selected} onChange={setSelected}>
          <Float
            as="div"
            className="relative"
            placement="bottom"
            offset={4}
            floatingAs={Fragment}
          >
            <Listbox.Button className="relative w-full bg-white pl-3.5 pr-10 py-2 text-left text-amber-500 text-sm leading-5 border border-gray-200 rounded-lg shadow-md">
              {selected.name}
              <span className="absolute inset-y-0 right-0 flex items-center pr-2 pointer-events-none">
                <HeroiconsChevronUpDown20Solid className="w-5 h-5 text-gray-400" aria-hidden="true" />
              </span>
            </Listbox.Button>

            <Listbox.Options className="w-full bg-white border border-gray-200 rounded-md shadow-lg overflow-hidden focus:outline-none">
              {people.map(person => (
                <Listbox.Option
                  key={person.id}
                  className={({ active }) =>
                    `relative block w-full pl-10 pr-3 py-2 text-left text-gray-600 text-sm cursor-default ${
                      active ? 'bg-amber-100 text-amber-700' : ''
                    } ${person.unavailable ? 'text-gray-300' : ''}`
                  }
                  value={person}
                  disabled={person.unavailable}
                >
                  {({ selected }) => (
                    <>
                      <span className={`block truncate ${selected ? 'font-medium' : 'font-normal'}`}>
                        { person.name }
                      </span>
                      {selected && (
                        <span className="absolute inset-y-0 left-0 flex items-center pl-3 text-amber-600">
                          <HeroiconsCheck20Solid className="w-5 h-5" aria-hidden="true" />
                        </span>
                      )}
                    </>
                  )}
                </Listbox.Option>
              ))}
            </Listbox.Options>
          </Float>
        </Listbox>
      </Block>

      <Block title="Adaptive width using JS" contentClass="h-[300px] p-4" data-testid="block-adaptive-width-js">
        <Listbox value={selected} onChange={setSelected}>
          <Float
            as="div"
            placement="bottom"
            offset={4}
            floatingAs={Fragment}
            adaptiveWidth
            portal
          >
            <Listbox.Button className="relative w-full bg-white pl-3.5 pr-10 py-2 text-left text-amber-500 text-sm leading-5 border border-gray-200 rounded-lg shadow-md">
              {selected.name}
              <span className="absolute inset-y-0 right-0 flex items-center pr-2 pointer-events-none">
                <HeroiconsChevronUpDown20Solid className="w-5 h-5 text-gray-400" aria-hidden="true" />
              </span>
            </Listbox.Button>

            <Listbox.Options className="bg-white border border-gray-200 rounded-md shadow-lg overflow-hidden focus:outline-none">
              {people.map(person => (
                <Listbox.Option
                  key={person.id}
                  className={({ active }) =>
                    `relative block w-full pl-10 pr-3 py-2 text-left text-gray-600 text-sm cursor-default ${
                      active ? 'bg-amber-100 text-amber-700' : ''
                    } ${person.unavailable ? 'text-gray-300' : ''}`
                  }
                  value={person}
                  disabled={person.unavailable}
                >
                  {({ selected }) => (
                    <>
                      <span className={`block truncate ${selected ? 'font-medium' : 'font-normal'}`}>
                        { person.name }
                      </span>
                      {selected && (
                        <span className="absolute inset-y-0 left-0 flex items-center pl-3 text-amber-600">
                          <HeroiconsCheck20Solid className="w-5 h-5" aria-hidden="true" />
                        </span>
                      )}
                    </>
                  )}
                </Listbox.Option>
              ))}
            </Listbox.Options>
          </Float>
        </Listbox>
      </Block>
    </>
  )
}
